kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.1625
    roll: 0
    pitch: 0
    yaw: 0
  upper_arm:
    x: 0
    y: 0
    z: 0
    roll: 1.570796327
    pitch: 0
    yaw: 0
  forearm:
    x: -0.425
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  wrist_1:
    x: -0.3922
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  wrist_2:
    x: 0
    y: 0
    z: 0.1333
    roll: 1.570796327
    pitch: 0
    yaw: 0
  wrist_3:
    x: 0
    y: 0
    z: 0.0997
    roll: -1.570796326589793
    pitch: 0
    yaw: 0
  hash: calib_12788084448423163542